# Generated by Django 5.2.7 on 2025-10-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='citizen_profiles/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='leader_profiles/'),
        ),
    ]
