# Generated by Django 5.2.7 on 2025-10-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve', '0002_citizenprofile_profile_picture_alter_issue_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='hometown_latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='hometown_longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='hometown_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
